#!/usr/bin/env ruby

require "pathname"

source_file = Pathname.glob("src/main/java/**/RustTokenId.java").first

constants_file = Pathname.glob("target/generated-sources/**/RustParserConstants.java").first
constants = constants_file.read.scan(%r{/\*\* (?:RegularExpression Id|End of File). \*/\n  int ([^ ]+)}).flatten
TOKEN_CATEGORIES = Hash[source_file.read.scan(/([A-Za-z0-9_]+)\(RustParserConstants\..*, TokenCategory\.(.*)\)/)]
TOKEN_CATEGORIES.default = "IDENTIFIER"
token_kind_declarations = constants.map {|c| "    #{c}(RustParserConstants.#{c}, TokenCategory.#{TOKEN_CATEGORIES[c]})"};
new_source = source_file.read.
        gsub(/.*[A-Z_]*\(RustParserConstants.*\n/,"").
        gsub(/(enum RustTokenId implements TokenId {\n\n)/, '\1' + token_kind_declarations.join(",\n") + ";\n")
puts "Writing constants to #{source_file}"
source_file.write(new_source)
